@startuml

state e0
state e1
state c0 <<choice>>
state e2
state c1 <<choice>>
state e3


[*] --> e0
e0 --> e1 : place token playerA
e1 --> c0 : [board contains 7 tokens]
e1 --> e0 : place token playerB
c0 --> [*] : [playerA wins]
c0 --> e2 : [else]
e2 --> c1 : place token playerB
c1 --> [*] : [playerB wins]
c1 --> [*]: [board is full & ! playerB wins]
c1 --> e3 : [else]
e3 --> c0 : place token playerA





@enduml