@startuml

state inDeck
state inStock
state inWaste
state inTableau
state inFoundation

state c1 <<choice>>

[*] --> inDeck : shuffle
inDeck --> c1 : distirbuted randomly
c1 --> inStock
c1 --> inTableau
inStock --> inWaste : stockToWaste

inWaste --> inFoundation : [existValidMove & !userIgnoresMove] / wasteToFoundation
inWaste --> inTableau : [existValidMove & !userIgnoresMove] / wasteToTableau
inWaste --> inStock : [isStockEmpty] / wasteToStock
inTableau --> inFoundation : [existValidMove & !userIgnoresMove] / tableauToFoundation
inTableau --> inTableau : [existValidMove & !userIgnoresMove] / tableauToTableau
inFoundation --> [*]

@enduml