@startuml

state e1 <<choice>>
state e2
state e3
state e4 <<choice>>
state e5
state e6

[*] --> e1
e1 --> e2 : [isMoveToPileAvailable & ! isMovementIgnored]
e2 --> e1 :  moveToPile
e1 --> e3 : [isMoveToFoundationAvailable & ! isMovementIgnored]
e3 --> e4: moveToFoundation
e4 --> e1
e4 --> [*]: [isWin]
e1 --> e5 : [isMoveToWasteAvailable & ! isMovementIgnored]]
e5 --> e1 : moveToWaste
e1 --> e6 : [else]
e6 --> [*] : surrender
e6 --> e1 : restoreDeck

@enduml