@startuml

state GAME_PREPARED
state c1 <<choice>>
state IN_GAME
state c2 <<choice>>

[*] --> GAME_PREPARED : distibute cards randomly
GAME_PREPARED --> c1
c1 --> c2 : [up to player]
c2 --> IN_GAME : [toFoundationMovementAvailable] / toFoundationMovement
c2 --> IN_GAME : [toTableauMovementAvailable] / toTableauMovement
c2 --> IN_GAME : [stockHasCards] / fromStockToWaste
c2 --> IN_GAME : [stockIsEmpty] / fromWasteToStock
IN_GAME --> [*] : [isWin]
IN_GAME --> [*] : [isSurrender]
IN_GAME --> c1

@enduml